# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'appQtDesigner.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1459, 847)
        MainWindow.setMaximumSize(QtCore.QSize(1459, 856))
        self.topwidget = QtWidgets.QWidget(MainWindow)
        self.topwidget.setObjectName("topwidget")
        self.pushButton = QtWidgets.QPushButton(self.topwidget)
        self.pushButton.setGeometry(QtCore.QRect(180, 120, 141, 41))
        self.pushButton.setMinimumSize(QtCore.QSize(141, 41))
        self.pushButton.setMaximumSize(QtCore.QSize(141, 41))
        self.pushButton.setStyleSheet("")
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.topwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1461, 851))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../../img/Alpha67 Laucher.png"))
        self.label.setObjectName("label")
        self.comboBox_2 = QtWidgets.QComboBox(self.topwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(420, 750, 241, 41))
        self.comboBox_2.setStyleSheet("background-color: rgb(124, 141, 130);\n"
"color: rgb(85, 255, 255);\n"
"selection-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(85, 255, 255);\n"
"font: 81 12pt \"Rockwell Extra Bold\";")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_3 = QtWidgets.QComboBox(self.topwidget)
        self.comboBox_3.setGeometry(QtCore.QRect(110, 750, 181, 41))
        self.comboBox_3.setStyleSheet("background-color: rgb(124, 141, 130);\n"
"color: rgb(85, 255, 255);\n"
"selection-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(85, 255, 255);\n"
"font: 81 12pt \"Rockwell Extra Bold\";")
        self.comboBox_3.setObjectName("comboBox_3")
        self.accounte = QtWidgets.QPushButton(self.topwidget)
        self.accounte.setGeometry(QtCore.QRect(20, 20, 121, 101))
        self.accounte.setStyleSheet("background-color: rgb(124, 141, 130);\n"
"color: rgb(85, 255, 255);\n"
"selection-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(85, 255, 255);\n"
"font: 81 12pt \"Rockwell Extra Bold\";")
        self.accounte.setText("")
        self.accounte.setObjectName("accounte")
        self.openFolder = QtWidgets.QPushButton(self.topwidget)
        self.openFolder.setGeometry(QtCore.QRect(770, 750, 241, 41))
        self.openFolder.setStyleSheet("background-color: rgb(124, 141, 130);\n"
"color: rgb(85, 255, 255);\n"
"selection-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(85, 255, 255);\n"
"font: 100 9pt \"Rockwell Extra Bold\";\n"
"border-color: rgb(143, 143, 143);")
        self.openFolder.setObjectName("openFolder")
        self.play = QtWidgets.QPushButton(self.topwidget)
        self.play.setGeometry(QtCore.QRect(1190, 680, 181, 81))
        self.play.setStyleSheet("QPushButton\n"
"{\n"
"color: rgb(255, 255, 76);\n"
"background-color: rgb(0, 176, 85);\n"
"selection-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(85, 255, 255);\n"
"border-color: rgb(143, 143, 143);\n"
"font: 100 25pt \"Rockwell Extra Bold\";\n"
"\n"
"}\n"
"\n"
"QPushButton::hover\n"
"{\n"
"color: rgb(255, 230, 76);\n"
"background-color: rgb(50, 200, 85);\n"
"font: 100 28pt \"Rockwell Extra Bold\";\n"
"}\n"
"QPushButton::pressed \n"
"{\n"
"background-color: rgb(50, 200, 85);\n"
"font: 100 20pt \"Rockwell Extra Bold\";\n"
"}")
        self.play.setObjectName("play")
        self.ram = QtWidgets.QLCDNumber(self.topwidget)
        self.ram.setGeometry(QtCore.QRect(1210, 500, 141, 41))
        self.ram.setObjectName("ram")
        self.cpu = QtWidgets.QLCDNumber(self.topwidget)
        self.cpu.setGeometry(QtCore.QRect(1210, 210, 141, 41))
        self.cpu.setObjectName("cpu")
        self.download = QtWidgets.QProgressBar(self.topwidget)
        self.download.setGeometry(QtCore.QRect(0, 700, 1181, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.download.sizePolicy().hasHeightForWidth())
        self.download.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.download.setFont(font)
        self.download.setStyleSheet("background-color: rgb(124, 141, 130);\n"
"color: rgb(85, 255, 255);\n"
"selection-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(85, 255, 255);\n"
"font: 81 12pt \"Rockwell Extra Bold\";")
        self.download.setProperty("value", 0)
        self.download.setTextDirection(QtWidgets.QProgressBar.BottomToTop)
        self.download.setObjectName("download")
        MainWindow.setCentralWidget(self.topwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "play"))
        self.openFolder.setText(_translate("MainWindow", "ouvrir dossier minecraft"))
        self.play.setText(_translate("MainWindow", "Play"))
